name: Build & Draft Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare repository in a single folder with plugin name
      run: |
        mkdir -p ./release/PaypalRefund
        rsync -av ./ ./release/PaypalRefund --exclude release --exclude .git --exclude .github

    - name: Create zip archive
      run: |
        cd release
        zip -r plugin.zip ./PaypalRefund
        ls -l plugin.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: true
        prerelease: false
        generate_release_notes: true
        files: ./release/plugin.zip
