name: Build & Draft Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Prepare repository in a single folder with plugin name
      run: |
        mkdir -p ./release/PaypalRefund
        rsync -av ./ ./release/PaypalRefund \
          --exclude release \
          --exclude .git \
          --exclude .github \
          --exclude .phpunit.result.cache \
          --exclude tests \
          --exclude phpunit.xml

    - name: Create zip archive
      run: |
        cd release
        zip -r plugin.zip ./PaypalRefund
        ls -l plugin.zip

    - name: Create Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: true
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: ./release/plugin.zip
